# Poetry Install, Lint and Typechecking
name: static-analysis
on: push

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
        os: [ubuntu-22.04, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: |
          python -m pip install poetry==2.1.1
      - name: Configure poetry
        run: |
          python -m poetry config virtualenvs.create true --local
          python -m poetry config virtualenvs.in-project true --local
          python -m poetry install --with=dev
      - uses: actions/cache@v3
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Install the project dependencies
        run: python -m poetry install --with dev
      - name: Lint with flake8
        run: python -m poetry run flake8 ./maimai_to_tachi
      - name: Type-checking package with mypy
        run: |
          python -m poetry run mypy --version
          python -m poetry run mypy ./maimai_to_tachi/
